CREATE USER JENKINS IDENTIFIED BY oracle
DEFAULT TABLESPACE JENKINS_DATA
TEMPORARY TABLESPACE TEMP;
ALTER USER JENKINS DEFAULT ROLE ALL;
grant connect to JENKINS;
grant all privileges to JENKINS;
grant SELECT_CATALOG_ROLE to JENKINS;
alter user JENKINS quota unlimited on JENKINS_DATA;
GRANT EXECUTE ON DBMS_LOCK TO JENKINS;